add action for release

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,10 +1,12 @@
-name: Tests
+name: Validation and Release
 
 on:
   push:
     branches:
       - main
       - dccboxed-*
+    tags:
+      - 'v*'
   pull_request:
     branches:
       - main
@@ -12,6 +14,7 @@ on:
 
 jobs:
   format:
+    name: Check Formatting
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -27,6 +30,7 @@ jobs:
       run: mvn -B -V formatter:validate
 
   lint:
+    name: Check Static Errors
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -50,6 +54,7 @@ jobs:
       run: reviewdog -f=checkstyle -reporter=github-check -fail-on-error < target/checkstyle-result.xml
 
   test:
+    name: Run Tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -64,4 +69,45 @@ jobs:
     - name: Run tests and collect coverage
       run: mvn -B test
     - name: Upload coverage to Codecov
+      if: github.event_name != 'push' || github.ref_type != 'tag' || !startsWith(github.ref_name, 'v')
       uses: codecov/codecov-action@v3
+
+  release:
+    name: Upload Release Package
+    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
+    needs:
+    - format
+    - lint
+    - test
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up JDK 11
+      uses: actions/setup-java@v3
+      with:
+        java-version: '11'
+        distribution: 'temurin'
+        cache: maven
+    - name: Maven install dependencies
+      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
+    - name: Build package
+      run: mvn -B package
+    - name: Extract and check package version
+      id: get-package
+      run: |
+        version=$(echo ${{github.ref_name}} | cut -c2-)
+        package="target/xmldsig-${version}.jar"
+        if test -f "${package}"; then
+          echo "::set-output name=package::$package"
+        else
+          echo "Error: expected package file at: ${package}" 1>&2
+          exit 1
+        fi
+    - name: Upload binaries to release
+      uses: svenstaro/upload-release-action@v2
+      with:
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
+        file: ${{ steps.get-package.outputs.package }}
+        tag: ${{ github.ref }}
+        overwrite: true
+        body: "Release ${{ github.ref_name }}"
